/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iaik.chille.election.userclient;

import iaik.chille.elections.common.Choice;
import iaik.chille.elections.common.Election;
import iaik.chille.elections.common.Elections;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author chille
 */
public class MainFrame2 extends java.awt.Frame {
  private static final long serialVersionUID = 1L;

  /**
   * Creates new form MainFrame2
   */
  public MainFrame2(Elections elections) {
    this.data = elections;
    initComponents();
    tableElection.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
      @Override
      public void valueChanged(ListSelectionEvent e)
      {
        table1SelectionChanged(e);
      }
    });
  }

  protected void table1SelectionChanged(ListSelectionEvent e)
  {

    if(tableElection.getSelectedRows().length != 1)
    {
      ctm.setData(null);
    }
    else
    {
      Election selectedElection = this.data.getElection().get(tableElection.getSelectedRow());
      //JOptionPane.showMessageDialog(null, jTable1.getSelectedRow()+" - "+ e.getFirstIndex()+"/"+e.getLastIndex()+
      // " ID: "+selectedElection.getId(), "Test Titel", JOptionPane.OK_CANCEL_OPTION);
      ctm.setData(selectedElection);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAction = new javax.swing.JPanel();
        btnVote = new javax.swing.JButton();
        btnRevert = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableElection = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChoice = new javax.swing.JTable();

        setName("");
        setPreferredSize(new java.awt.Dimension(452, 443));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        btnVote.setText("Vote");
        btnVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoteActionPerformed(evt);
            }
        });
        panelAction.add(btnVote);

        btnRevert.setText("Revert");
        btnRevert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevertActionPerformed(evt);
            }
        });
        panelAction.add(btnRevert);

        btnVerify.setText("Verify");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        panelAction.add(btnVerify);

        btnTest.setText("Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });
        panelAction.add(btnTest);

        add(panelAction, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 202));

        tableElection.setModel(new iaik.chille.election.userclient.ElectionTableModel(data));
        jScrollPane1.setViewportView(tableElection);

        jPanel1.add(jScrollPane1);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 202));

        tableChoice.setModel(ctm);
        jScrollPane2.setViewportView(tableChoice);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * Exit the Application
   */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      System.exit(0);
    }//GEN-LAST:event_exitForm

  private void btnVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoteActionPerformed
    if(tableElection.getSelectedRows().length != 1)
    {
      ClientHandler.getInstance().alert("Error", "You can only vote for one election per time.");
    }
    else if(tableChoice.getSelectedRows().length != 1)
    {
      ClientHandler.getInstance().alert("Error", "You can only select one answer for an election.");
    }
    else
    {
      Election selectedElection = this.data.getElection().get(tableElection.getSelectedRow());
      Choice selectedChoice = selectedElection.getChoice().get(tableChoice.getSelectedRow());
      
      ClientHandler.getInstance().vote(selectedElection, selectedChoice);
    }
  }//GEN-LAST:event_btnVoteActionPerformed

  private void btnRevertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevertActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnRevertActionPerformed

  private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnVerifyActionPerformed

  private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
    ClientHandler.getInstance().test(null, null);
  }//GEN-LAST:event_btnTestActionPerformed

    private Elections data = null;
    private ChoiceTableModel ctm = new ChoiceTableModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevert;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnVerify;
    private javax.swing.JButton btnVote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelAction;
    private javax.swing.JTable tableChoice;
    private javax.swing.JTable tableElection;
    // End of variables declaration//GEN-END:variables
}
