/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iaik.chille.election.userclient;

import java.util.Vector;

/**
 *
 * @author chille
 */
public class XMLViewer extends java.awt.Frame {

  /**
   * Creates new form XMLViewer
   */
  Vector<XMLStruct> v = new Vector<> ();
  Vector<String> v2 = new Vector<> ();
  public XMLViewer() {
    initComponents();
    xmlList.setListData(v);
    jList2.setListData(v2);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        textArea1 = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        xmlList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, xmlList, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.xml}"), textArea1, org.jdesktop.beansbinding.BeanProperty.create("text"), "");
        binding.setSourceNullValue("empty");
        bindingGroup.addBinding(binding);

        add(textArea1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(xmlList);

        add(jScrollPane1, java.awt.BorderLayout.WEST);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, xmlList, eLProperty, jList2);
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * Exit the Application
   */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      this.setVisible(false);
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.TextArea textArea1;
    private javax.swing.JList xmlList;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables



    public void addXML(String header, String xml)
    {
      v.add(new XMLStruct(header, xml));
      xmlList.setListData(v);
      //jList1.add(new XMLStruct(header, xml));
    }

    private static XMLViewer _instance = new XMLViewer();
    public static XMLViewer getInstance()
    {
      return _instance;
    }

}

